#!/bin/bash

# COMANDOS COMPLETOS PARA SOLUCIONAR EL SERVIDOR VPS
# Ejecutar estos comandos uno por uno en el VPS

echo "========================================"
echo "COMANDOS COMPLETOS PARA SOLUCIÓN MANUAL"
echo "========================================"
echo ""

echo "CONECTARSE AL VPS:"
echo "ssh root@213.199.39.147"
echo ""

echo "========================================"
echo "PASO 1: IR AL DIRECTORIO CORRECTO"
echo "========================================"
echo "cd /home/radioapp/radio-recorder/app"
echo ""

echo "========================================"
echo "PASO 2: VERIFICAR ARCHIVOS"
echo "========================================"
echo "ls -la"
echo ""

echo "========================================"
echo "PASO 3: HACER BACKUP"
echo "========================================"
echo "cp server-vps-organized-correct-path.js server-vps-organized-correct-path.js.backup"
echo ""

echo "========================================"
echo "PASO 4: VERIFICAR CONTENIDO ACTUAL"
echo "========================================"
echo "head -5 server-vps-organized-correct-path.js"
echo ""

echo "========================================"
echo "PASO 5: AÑADIR DOTENV AL INICIO"
echo "========================================"
echo "sed -i '1i require(\"dotenv\").config();' server-vps-organized-correct-path.js"
echo ""

echo "========================================"
echo "PASO 6: VERIFICAR QUE SE AÑADIÓ"
echo "========================================"
echo "head -5 server-vps-organized-correct-path.js"
echo ""

echo "========================================"
echo "PASO 7: VERIFICAR SINTAXIS"
echo "========================================"
echo "node -c server-vps-organized-correct-path.js"
echo ""

echo "========================================"
echo "PASO 8: VERIFICAR VARIABLES DE ENTORNO"
echo "========================================"
echo "cat .env"
echo ""

echo "========================================"
echo "PASO 9: PROBAR CARGA DE DOTENV"
echo "========================================"
echo "node -e \"require('dotenv').config(); console.log('SUPABASE_URL:', process.env.SUPABASE_URL);\""
echo ""

echo "========================================"
echo "PASO 10: PROBAR EJECUCIÓN MANUAL"
echo "========================================"
echo "sudo -u radioapp timeout 10s node server-vps-organized-correct-path.js"
echo ""

echo "========================================"
echo "PASO 11: SI FUNCIONA, REINICIAR SERVICIO"
echo "========================================"
echo "systemctl restart radio-recording-organized.service"
echo ""

echo "========================================"
echo "PASO 12: VERIFICAR ESTADO DEL SERVICIO"
echo "========================================"
echo "systemctl status radio-recording-organized.service"
echo ""

echo "========================================"
echo "PASO 13: VER LOGS"
echo "========================================"
echo "journalctl -u radio-recording-organized.service -n 20 --no-pager"
echo ""

echo "========================================"
echo "PASO 14: PROBAR ENDPOINT"
echo "========================================"
echo "curl http://localhost:5000/health"
echo ""

echo "========================================"
echo "PASO 15: PROBAR ENDPOINT EXTERNO"
echo "========================================"
echo "curl http://213.199.39.147:5000/health"
echo ""

echo "========================================"
echo "COMANDOS ADICIONALES SI HAY PROBLEMAS"
echo "========================================"
echo ""
echo "Verificar si el puerto está en uso:"
echo "netstat -tlnp | grep :5000"
echo ""
echo "Matar procesos node si es necesario:"
echo "pkill -f 'node server-vps-organized-correct-path.js'"
echo ""
echo "Verificar logs completos:"
echo "journalctl -u radio-recording-organized.service -f"
echo ""
echo "Si todo falla, restaurar backup:"
echo "cp server-vps-organized-correct-path.js.backup server-vps-organized-correct-path.js"
echo ""

echo "========================================"
echo "RESULTADO ESPERADO"
echo "========================================"
echo "✅ El servidor debe mostrar:"
echo "🚀 Servidor de grabación organizado iniciado en puerto 5000"
echo "📁 Directorio base: /home/radioapp/radio-recorder/recordings"
echo "📊 Estructura: /recordings/YYYY-MM-DD/radio_id/"
echo ""
echo "✅ El servicio debe mostrar:"
echo "Active: active (running)"
echo "✅ El endpoint health debe responder:"
echo "{\"status\":\"OK\",\"timestamp\":\"...\",\"active_recordings\":0}"
echo ""

echo "========================================"
echo "FIN DE LOS COMANDOS"
echo "========================================"