#!/bin/bash

# SOLUCIÓN FINAL: CAMBIAR PUERTO Y VERIFICAR CONFLICTOS

set -e

echo "========================================"
echo "SOLUCIÓN FINAL: CAMBIAR PUERTO Y VERIFICAR"
echo "========================================"
echo ""

echo "PASO 1: VERIFICAR QUÉ ESTÁ EN EL PUERTO 5000"
echo "========================================"
echo "netstat -tlnp | grep :5000"
echo ""

echo "PASO 2: MATAR PROCESOS EN PUERTO 5000"
echo "========================================"
echo "sudo fuser -k 5000/tcp"
echo ""

echo "PASO 3: CAMBIAR PUERTO DEL SERVIDOR A 5001"
echo "========================================"
echo "cd /home/radioapp/radio-recorder/app"
echo ""

echo "PASO 4: EDITAR ARCHIVO .ENV"
echo "========================================"
echo "cat > .env << 'EOF'"
echo "# Configuración de Supabase para VPS"
echo "SUPABASE_URL=http://supabasekong-u4g0k80skos0s0gww8wks800.147.93.182.94.sslip.io"
echo "SUPABASE_ANON_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc2NDEwNzE2MCwiZXhwIjo0OTE5NzgwNzYwLCJyb2xlIjoiYW5vbiJ9.52uLuYBh1c1_wHOgGkj4wPMzRWd6-bashlBU3p90wGw"
echo ""
echo "# Configuración del servidor"
echo "PORT=5001"
echo "RECORDINGS_DIR=/home/radioapp/radio-recorder/recordings"
echo "EOF"
echo ""

echo "PASO 5: ACTUALIZAR SERVICIO SYSTEMD"
echo "========================================"
echo "cat > /etc/systemd/system/radio-recording-organized.service << 'EOF'"
echo "[Unit]"
echo "Description=Radio Recording Server Organized"
echo "After=network.target"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=radioapp"
echo "Group=radioapp"
echo "WorkingDirectory=/home/radioapp/radio-recorder/app"
echo "Environment=NODE_ENV=production"
echo "Environment=SUPABASE_URL=http://supabasekong-u4g0k80skos0s0gww8wks800.147.93.182.94.sslip.io"
echo "Environment=SUPABASE_ANON_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc2NDEwNzE2MCwiZXhwIjo0OTE5NzgwNzYwLCJyb2xlIjoiYW5vbiJ9.52uLuYBh1c1_wHOgGkj4wPMzRWd6-bashlBU3p90wGw"
echo "ExecStart=/usr/bin/node server-vps-organized-correct-path.js"
echo "Restart=always"
echo "RestartSec=10"
echo "StandardOutput=journal"
echo "StandardError=journal"
echo "SyslogIdentifier=radio-recording-organized"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""

echo "PASO 6: RECARGAR SYSTEMD"
echo "========================================"
echo "systemctl daemon-reload"
echo ""

echo "PASO 7: PROBAR EJECUCIÓN MANUAL EN PUERTO 5001"
echo "========================================"
echo "sudo -u radioapp timeout 10s node server-vps-organized-correct-path.js"
echo ""

echo "PASO 8: SI FUNCIONA, INICIAR SERVICIO"
echo "========================================"
echo "systemctl restart radio-recording-organized.service"
echo ""

echo "PASO 9: VERIFICAR ESTADO"
echo "========================================"
echo "systemctl status radio-recording-organized.service"
echo ""

echo "PASO 10: PROBAR ENDPOINT EN NUEVO PUERTO"
echo "========================================"
echo "curl http://localhost:5001/health"
echo ""

echo "PASO 11: HABILITAR PUERTO 5001 EN FIREWALL"
echo "========================================"
echo "ufw allow 5001/tcp"
echo ""

echo "PASO 12: PROBAR ENDPOINT EXTERNO"
echo "========================================"
echo "curl http://213.199.39.147:5001/health"
echo ""

echo "========================================"
echo "COMANDOS PARA ACTUALIZAR FRONTEND"
echo "========================================"
echo ""
echo "En tu computadora local, actualiza el archivo:"
echo "app/app/api/recording-vps-fixed/route.ts"
echo ""
echo "Cambia la línea:"
echo "const VPS_API_URL = 'http://213.199.39.147:5000';"
echo ""
echo "Por:"
echo "const VPS_API_URL = 'http://213.199.39.147:5001';"
echo ""

echo "========================================"
echo "RESULTADO ESPERADO FINAL"
echo "========================================"
echo "✅ El servidor debe mostrar:"
echo "🚀 Servidor de grabación organizado iniciado en puerto 5001"
echo ""
echo "✅ El servicio debe mostrar:"
echo "Active: active (running)"
echo ""
echo "✅ El endpoint debe responder:"
echo "{\"status\":\"OK\",\"timestamp\":\"...\",\"active_recordings\":0}"
echo ""
echo "✅ El frontend debe conectar a http://213.199.39.147:5001"
echo ""

echo "========================================"
echo "FIN DE LA SOLUCIÓN"
echo "========================================"